# Site settings
title: Béatrice Lajous
email: glovesmore@gmail.com
description: > # this means to ignore newlines until "baseurl:"
Hi, I'm Béatrice, an email strategist, musician and collage artist located in Brighton, East Sussex (England).
I'm currently working on Space for Imagination, a walking workshop with the artist Esther MacManus.
I'm also curating sounds for Flâneurs, a monthly radio show, broadcasted by Resonance Extra. 
I volunteer  at Fabrica, a local contemporary art gallery. I've also helped promote Diep~Haven.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "glovesmore.github.io" # the base hostname & protocol for your site
twitter_username: glovesmore
github_username: glovesmore
tumblr_username: capt-lovelace

# Build settings
markdown: kramdown
